print ('')
print ('		Kanwal Naz		')
print ('')
print ('Address: '+'House D-01 Block 04 saadi Town Karachi')
print ('Contact: '+ '0347-2384960')
print ('Email: '+ 'kanwaalnaz@gmail.com')
print ('')
print ('		Experience		')
print ('')
print ('EFU General Insurance')
print ('Designation:' + ' Manager')
print ('Period:' + ' 1st January 2018 till present')
print ('')
print ('		Qualification		')
print ('')
print ('Masters in Engineering')
print ('University: NED University')
print ('Major: Data Engineering')
print ('3.94 CGPA')
print ('')
print ('Bachelors in Engineering')
print ('University: NED University')
print ('Major: Electronics Engineering')
print ('3.60 CGPA')
print ('')
print ('Intermediate')
print ('College: Gulshan College')
print ('Major: Pre-Engineering')
print ('83%')
print ('')
print ('Matriculation')
print ('School: Army Public School')
print ('Major: Science')
print ('86%')
print ('')

